#!/usr/bin/env bash
#
# restart.sh — clean restart (or first boot) of the Route Plotter dev server.
#
# Codifies the recovery playbook in DEV-INFRASTRUCTURE.md: stop any running dev
# server (the port 3000 listener AND its `node build.js --watch` parent),
# (optionally) clear the generated docs/ output, boot `npm run dev`, then wait
# until the server actually answers HTTP 200 before reporting "ready" — because
# the server can print "Serving…" and then crash (see decision-log 2026-06-16).
#
# Usage:
#   ./scripts/restart.sh              # stop running dev server, boot, verify readiness
#   ./scripts/restart.sh --hard-reset # also delete docs/ (regenerated on boot)
#   ./scripts/restart.sh --help
#
# Runs in the foreground; Ctrl-C stops the server cleanly. Works from any
# directory. If the executable bit is lost (e.g. via OneDrive sync), run it
# with: bash scripts/restart.sh

set -euo pipefail

PORT=3000
URL="http://localhost:${PORT}"
READY_TIMEOUT=30   # seconds to wait for the first HTTP 200

# Resolve the project root (this script lives in <root>/scripts) so the script
# works no matter which directory it is invoked from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

HARD_RESET=false
DEV_PID=""

usage() {
  cat <<EOF
restart.sh — clean restart/boot of the Route Plotter dev server

Usage:
  ./scripts/restart.sh              Stop any running dev server, boot it, verify it is ready
  ./scripts/restart.sh --hard-reset Also delete the generated docs/ folder before booting
  ./scripts/restart.sh --help       Show this help

Notes:
  - Stops only this project's dev server — the port ${PORT} listener and its
    node build.js --watch parent; never a broad "pkill node".
  - --hard-reset deletes only docs/ (regenerated by the build). Source files,
    version.json and _Joe/ are never touched.
  - No hot reload: hard-refresh the browser (Cmd+Shift+R) after it boots.
EOF
}

for arg in "$@"; do
  case "${arg}" in
    --hard-reset) HARD_RESET=true ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: ${arg}" >&2; usage; exit 1 ;;
  esac
done

# Find the dev server's process tree. esbuild binds the port from a child
# "service" process, so the port listener (lsof) is esbuild, while its parent —
# `node build.js --watch` — is what `npm run dev` actually launched. Killing only
# the port listener leaves that node parent orphaned (decision-log 2026-06-17),
# so we always target both. Scoped to this project's `build.js --watch` — never a
# broad `pkill node`.
dev_pids() {
  {
    lsof -ti :"${PORT}" 2>/dev/null || true
    pgrep -f 'build\.js --watch' 2>/dev/null || true
  } | sort -u
}

# Stop the dev server: graceful TERM, then KILL only survivors after a grace
# period. Idempotent — safe to call when nothing is running.
stop_dev() {
  local pids
  pids="$(dev_pids)"
  if [[ -z "${pids}" ]]; then
    return 0
  fi
  echo "🛑 Stopping dev server (PIDs: ${pids//$'\n'/ })"
  # shellcheck disable=SC2086
  kill ${pids} 2>/dev/null || true
  for _ in 1 2 3 4 5; do
    sleep 0.4
    pids="$(dev_pids)"
    if [[ -z "${pids}" ]]; then
      return 0
    fi
  done
  echo "⚠️  Forcing kill of survivors: ${pids//$'\n'/ }" >&2
  # shellcheck disable=SC2086
  kill -9 ${pids} 2>/dev/null || true
}

# On Ctrl-C / TERM, stop the dev server this script owns and exit cleanly.
cleanup() {
  trap - INT TERM
  echo ""
  echo "🧹 Shutting down dev server…"
  stop_dev
  exit 0
}
trap cleanup INT TERM

cd "${ROOT_DIR}"

stop_dev

if [[ "${HARD_RESET}" == true ]]; then
  echo "🗑️  Hard reset: removing docs/ (regenerated on boot)"
  rm -rf "${ROOT_DIR}/docs"
fi

echo "🚀 Booting dev server (npm run dev)…"
npm run dev &
DEV_PID=$!

# Verify readiness: poll until the server answers HTTP 200, not just launches.
echo "⏳ Waiting for ${URL} to answer (up to ${READY_TIMEOUT}s)…"
ready=false
attempts=$(( READY_TIMEOUT * 2 ))   # poll every 0.5s
while (( attempts > 0 )); do
  if ! kill -0 "${DEV_PID}" 2>/dev/null; then
    echo "❌ Dev server exited before becoming ready — check the log above." >&2
    exit 1
  fi
  if curl -fsS -o /dev/null "${URL}/" 2>/dev/null; then
    ready=true
    break
  fi
  sleep 0.5
  attempts=$(( attempts - 1 ))
done

if [[ "${ready}" == true ]]; then
  version="$(curl -fsS "${URL}/" 2>/dev/null \
    | sed -n 's/.*<title>Route Plotter \(v[0-9.]*\).*/\1/p' | head -n1 || true)"
  echo "✅ Ready at ${URL} ${version:+(${version})}"
  echo "💡 Hard-refresh the browser (Cmd+Shift+R) — no hot reload."
else
  echo "⚠️  ${URL} did not answer within ${READY_TIMEOUT}s. The server is still" >&2
  echo "    running below; check the log for errors." >&2
fi

# Stay in the foreground tied to the server; Ctrl-C triggers cleanup above.
wait "${DEV_PID}"
