#!/usr/bin/env node
// Directory inventory from Git's tracked + untracked non-ignored files.
// Non-Git fallback skips common generated directories; never follows symlinks.
import { readFileSync, existsSync, writeFileSync, readdirSync, lstatSync, realpathSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, relative } from 'node:path';
import { options, sections } from './ledger.mjs';
const args = options(['depth']);
const root = args.root, depth = Number(args.depth || 2);
if (!Number.isInteger(depth) || depth < 1 || depth > 10) throw Error('--depth must be an integer from 1 to 10');
const out = join(root, 'project', 'structure.md');
const SKIP = new Set(['node_modules', '.git', 'dist', 'build', 'coverage', '.cache', 'project', '.claude', '.codex']);
const existing = existsSync(out) ? readFileSync(out, 'utf8') : '';
const roles = new Map([...existing.matchAll(/^\| `([^`]+)` \| \d+ \| (.+?) \|$/gm)].map((m) => [m[1], m[2]]));
const kept = sections(existing), counts = new Map([['./', 0]]);
const eligible = (p) => !p.split('/').some((s) => SKIP.has(s) || s.startsWith('.'));
let files = [], mode = 'Git tracked + untracked, respecting ignores';
try {
  const top = execFileSync('git', ['rev-parse', '--show-toplevel'], { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  if (realpathSync(root) !== realpathSync(top)) throw Error('not repository root');
  files = execFileSync('git', ['ls-files', '-co', '--exclude-standard', '-z'], { cwd: root, encoding: 'utf8' }).split('\0').filter(Boolean);
} catch (error) {
  if (existsSync(join(root, '.git'))) throw error;
  mode = 'non-Git fallback; common generated and hidden directories excluded';
  const walk = (dir) => {
    for (const ent of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, ent.name), rel = relative(root, p).split('\\').join('/');
      if (!eligible(rel) || ent.isSymbolicLink()) continue;
      if (ent.isDirectory()) walk(p); else if (ent.isFile()) files.push(rel);
    }
  };
  walk(root);
}
for (const file of new Set(files)) {
  if (!eligible(file)) continue;
  // Check each component: tracked paths must not traverse a replaced directory symlink.
  const parts = file.split('/'); let p = root, safe = true;
  for (const part of parts) { p = join(p, part); if (!existsSync(p) || lstatSync(p).isSymbolicLink()) { safe = false; break; } }
  if (!safe) continue;
  if (parts.length === 1) counts.set('./', counts.get('./') + 1);
  for (let d = 1; d < parts.length && d <= depth; d++) {
    const dir = parts.slice(0, d).join('/') + '/'; counts.set(dir, (counts.get(dir) || 0) + 1);
  }
}
const rows = [...counts].sort(([a], [b]) => a.localeCompare(b));
for (const [path] of rows) if (/[|`\r\n]/.test(path)) throw Error(`path cannot be represented in the structure table: ${JSON.stringify(path)}`);
const title = (existing.match(/^# Structure — (.+)$/m) || [, '{project name}'])[1];
const entry = kept.get('Entry points') || '- {file} — {what it starts}';
writeFileSync(out, `# Structure — ${title}\n\n<!-- Generated by tools/structure.mjs. ${mode}. Directory counts include descendants; ./ counts root files only. No symlinks; any existing Where to look first section is not carried forward. -->\n\n| Path | Files | Role |\n| --- | --- | --- |\n${rows.map(([path, count]) => `| \`${path}\` | ${count} | ${roles.get(path) || '{what lives here, one line}'} |`).join('\n')}\n\n## Entry points\n\n${entry}\n`);
console.log(`structure: ${rows.length} rows; ${mode}; roles and entry sections kept`);
